const mongoose = require("mongoose");

// 1. Define Schema (Must match products.js EXACTLY)
const productSchema = new mongoose.Schema({
  title: String,
  price: Number,
  originalPrice: Number,
  category: String,
  brand: String,
  image: String,
  images: [String],
  rating: { type: Number, default: 4.5 },
  reviews: { type: Number, default: 0 },
  description: String,
  isNewArrival: { type: Boolean, default: false },
  isBestSeller: { type: Boolean, default: false },
  stock: { type: Number, default: 10 },
  inStock: { type: Boolean, default: true },
  sizes: [String],
  colors: [String],
  // --- NEW FIELDS ---
  tags: [String],
  frequentlyBoughtTogether: [
    { type: mongoose.Schema.Types.ObjectId, ref: "Product" },
  ],
});

const Product =
  mongoose.models.Product || mongoose.model("Product", productSchema);

// 2. The Data (Now with Tags!)
const seedProducts = [
  // --- BATS ---
  {
    title: "SG HP33 Kashmir Willow",
    price: 4999,
    originalPrice: 6999,
    category: "bats",
    brand: "sg",
    image: "images/SS.png",
    images: ["images/SS.png", "images/bats.png"],
    rating: 4.5,
    reviews: 125,
    isBestSeller: true,
    description: "Hand-crafted Kashmir Willow bat with superior balance.",
    stock: 15,
    sizes: ["SH", "Harrow", "6"],
    colors: ["Natural"],
    tags: ["kashmir-willow", "beginner", "balance"],
  },
  {
    title: "Kookaburra Kahuna Pro",
    price: 8999,
    originalPrice: 10999,
    category: "bats",
    brand: "kookaburra",
    image: "images/Kookabura.png",
    images: ["images/Kookabura.png", "images/bats.png"],
    rating: 5,
    reviews: 89,
    isNewArrival: true,
    description:
      "The iconic Kahuna. Mid-blade sweet spot for all-round stroke play.",
    stock: 5,
    sizes: ["SH", "LH"],
    colors: ["Green/White"],
    tags: ["english-willow", "pro", "power"],
  },
  {
    title: "SS Ton Retro Classic",
    price: 11500,
    originalPrice: 13999,
    category: "bats",
    brand: "ss",
    image: "images/ssretro.png",
    images: ["images/ssretro.png", "images/SS.png"],
    rating: 4.8,
    reviews: 45,
    description: "Grade 1 English Willow. Huge edges and massive power.",
    stock: 8,
    sizes: ["SH"],
    colors: ["Natural"],
    tags: ["english-willow", "classic", "power"],
  },
  {
    title: "MRF Grand Edition",
    price: 22000,
    originalPrice: 24999,
    category: "bats",
    brand: "mrf",
    image: "images/mrf.png",
    images: ["images/mrf.png", "images/bats.png"],
    rating: 5,
    reviews: 32,
    description:
      "Virat Kohli's choice. Premium English Willow with lightweight pickup.",
    stock: 3,
    sizes: ["SH", "LH"],
    colors: ["Red/White"],
    tags: ["virat-kohli", "english-willow", "premium"],
  },
  {
    title: "Gray-Nicolls Cobra",
    price: 7499,
    originalPrice: 9999,
    category: "bats",
    brand: "gray-nicolls",
    image: "images/grayniccols.png",
    images: ["images/grayniccols.png"],
    rating: 4.6,
    reviews: 67,
    description: "Low-profile sweet spot, perfect for front-foot drives.",
    stock: 12,
    sizes: ["SH", "Harrow"],
    colors: ["Blue/Silver"],
    tags: ["english-willow", "low-profile", "drive"],
  },
  {
    title: "BAS Vampire SR23",
    price: 7499,
    originalPrice: 9999,
    category: "bats",
    brand: "bas",
    image: "images/BAS.png",
    images: ["images/BAS.png"],
    rating: 4.5,
    reviews: 156,
    description: "Legendary BAS profile with thick edges.",
    stock: 0,
    sizes: ["SH"],
    colors: ["Red/Black"],
    tags: ["kashmir-willow", "thick-edges"],
  },
  {
    title: "Adidas Incurza 4.0",
    price: 6500,
    originalPrice: 8000,
    category: "bats",
    brand: "adidas",
    image: "images/adbats.jpg",
    images: ["images/adbats.jpg"],
    rating: 4.3,
    reviews: 40,
    description: "Designed for the modern T20 power hitter.",
    stock: 20,
    sizes: ["SH", "6"],
    colors: ["Acid Red"],
    tags: ["t20", "power", "modern"],
  },
  {
    title: "DSC Blak 300",
    price: 5500,
    originalPrice: 7000,
    category: "bats",
    brand: "dsc",
    image: "images/dbats.jpg",
    images: ["images/dbats.jpg"],
    rating: 4.4,
    reviews: 25,
    description: "Powerful profile with high spine for extra punch.",
    stock: 10,
    sizes: ["SH"],
    colors: ["Black"],
    tags: ["beginner", "budget", "power"],
  },

  // --- BALLS ---
  {
    title: "SG Test Cricket Ball",
    price: 899,
    originalPrice: 1199,
    category: "balls",
    brand: "sg",
    image: "images/sgred.png",
    images: ["images/sgred.png"],
    rating: 5,
    reviews: 78,
    isBestSeller: true,
    description: "Official Test match ball. High-quality alum tanned leather.",
    stock: 100,
    sizes: ["Standard"],
    colors: ["Red"],
    tags: ["leather", "test-match", "professional"],
  },
  {
    title: "Kookaburra Turf White",
    price: 1299,
    originalPrice: 1699,
    category: "balls",
    brand: "kookaburra",
    image: "images/kookaburaball.png",
    images: ["images/kookaburaball.png"],
    rating: 5,
    reviews: 156,
    description: "Regulation white ball for T20/ODI cricket. Excellent swing.",
    stock: 50,
    sizes: ["Standard"],
    colors: ["White"],
    tags: ["leather", "white-ball", "odi"],
  },
  {
    title: "SG Pink Leather Ball",
    price: 499,
    originalPrice: 650,
    category: "balls",
    brand: "sg",
    image: "images/sgpink.png",
    images: ["images/sgpink.png"],
    rating: 4.2,
    reviews: 200,
    description: "Durable 4-piece ball perfect for club matches and nets.",
    stock: 0,
    sizes: ["Standard"],
    colors: ["Pink"],
    tags: ["leather", "practice", "pink"],
  },
  {
    title: "Heavy Tennis Ball (Pack of 5)",
    price: 540,
    originalPrice: 720,
    category: "balls",
    brand: "dsc",
    image: "images/tball.png",
    images: ["images/tball.png"],
    rating: 4.5,
    reviews: 500,
    description: "Heavy duty tennis balls for box cricket.",
    stock: 200,
    sizes: ["Pack of 5"],
    colors: ["Red", "Yellow"],
    tags: ["tennis", "box-cricket", "heavy"],
  },
  {
    title: "Training Synthetic Ball",
    price: 150,
    originalPrice: 250,
    category: "balls",
    brand: "generic",
    image: "images/synthetic.png",
    images: ["images/synthetic.png"],
    rating: 3.8,
    reviews: 40,
    description: "All-weather synthetic ball for practice.",
    stock: 60,
    sizes: ["Standard"],
    colors: ["Red", "Yellow"],
    tags: ["synthetic", "practice", "weather-proof"],
  },

  // --- PADS ---
  {
    title: "Kookaburra Batting Pads",
    price: 2999,
    originalPrice: 3999,
    category: "pads",
    brand: "kookaburra",
    image: "images/pads.png",
    images: ["images/pads.png"],
    rating: 4,
    reviews: 92,
    description: "Lightweight foam pads with traditional cane protection.",
    stock: 15,
    sizes: ["Boys", "Youth", "Adult"],
    colors: ["White", "Blue", "Green"],
    tags: ["protection", "lightweight", "foam"],
  },
  {
    title: "Moonwalkr Thigh Pad Combo",
    price: 2800,
    originalPrice: 3200,
    category: "pads",
    brand: "moonwalkr",
    image: "images/mthighpad.jpg",
    images: ["images/mthighpad.jpg"],
    rating: 4.9,
    reviews: 110,
    isBestSeller: true,
    description: "Futuristic slim design. Integrated inner/outer thigh guard.",
    stock: 25,
    sizes: ["S", "M", "L"],
    colors: ["Blue", "White", "Black"],
    tags: ["protection", "thigh-guard", "slim"],
  },
  {
    title: "SS Limited Edition Pads",
    price: 3200,
    originalPrice: 4000,
    category: "pads",
    brand: "ss",
    image: "images/sspad.png",
    images: ["images/sspad.png"],
    rating: 4.5,
    reviews: 56,
    description: "Premium PU facing with cotton filled knee rolls.",
    stock: 8,
    sizes: ["Adult", "Large Adult"],
    colors: ["White"],
    tags: ["protection", "premium", "traditional"],
  },
  {
    title: "SG Test Thigh Guard",
    price: 899,
    originalPrice: 1199,
    category: "pads",
    brand: "sg",
    image: "images/thighpad.png",
    images: ["images/thighpad.png"],
    rating: 4,
    reviews: 71,
    description: "Standard pre-shaped thigh guard with soft towel backing.",
    stock: 40,
    sizes: ["Standard"],
    colors: ["White"],
    tags: ["protection", "basic", "thigh-guard"],
  },

  // --- GLOVES ---
  {
    title: "BAS Vampire Batting Gloves",
    price: 1999,
    originalPrice: 2499,
    category: "gloves",
    brand: "bas",
    image: "images/gloves.png",
    images: ["images/gloves.png"],
    rating: 5,
    reviews: 145,
    isBestSeller: true,
    description:
      "Super soft sheep leather palm with sausage finger protection.",
    stock: 30,
    sizes: ["Youth", "Adult"],
    colors: ["White/Red"],
    tags: ["protection", "leather-palm", "comfort"],
  },
  {
    title: "Kookaburra Pro Keeper Gloves",
    price: 2799,
    originalPrice: 3699,
    category: "gloves",
    brand: "kookaburra",
    image: "images/kgloves.png",
    images: ["images/kgloves.png"],
    rating: 4.5,
    reviews: 84,
    isNewArrival: true,
    description: "Short cuff design with octopus grip for superior catching.",
    stock: 10,
    sizes: ["Adult"],
    colors: ["Green/White"],
    tags: ["keeping", "grip", "pro"],
  },
  {
    title: "SS Millenium Pro Gloves",
    price: 2200,
    originalPrice: 2600,
    category: "gloves",
    brand: "ss",
    image: "images/ssmgloves.png",
    images: ["images/ssmgloves.png"],
    rating: 4.6,
    reviews: 40,
    description: "Multi-flex points for unrestricted hand movement.",
    stock: 20,
    sizes: ["Boys", "Adult"],
    colors: ["Blue/White"],
    tags: ["protection", "flexible", "batting"],
  },
  {
    title: "SG Savage Lite Gloves",
    price: 1500,
    originalPrice: 1999,
    category: "gloves",
    brand: "sg",
    image: "images/sgggloves.png",
    images: ["images/sgggloves.png"],
    rating: 4.2,
    reviews: 60,
    description: "Lightweight gloves for club cricket.",
    stock: 0,
    sizes: ["Adult"],
    colors: ["White"],
    tags: ["protection", "lightweight", "budget"],
  },

  // --- HELMETS ---
  {
    title: "SG Aerotech Helmet",
    price: 3499,
    originalPrice: 4499,
    category: "helmets",
    brand: "sg",
    image: "images/helmet.png",
    images: ["images/helmet.png"],
    rating: 4.5,
    reviews: 67,
    description: "High impact polypropylene shell with sweat absorbent lining.",
    stock: 12,
    sizes: ["S", "M", "L"],
    colors: ["Navy", "Black"],
    tags: ["safety", "helmet", "lightweight"],
  },
  {
    title: "Shrey Master Class Air",
    price: 5500,
    originalPrice: 6500,
    category: "helmets",
    brand: "shrey",
    image: "images/shhelmet.png",
    images: ["images/shhelmet.png"],
    rating: 4.9,
    reviews: 45,
    isNewArrival: true,
    description: "Lightweight titanium grille. Choice of international pros.",
    stock: 5,
    sizes: ["M", "L", "XL"],
    colors: ["Green", "Navy", "Yellow"],
    tags: ["safety", "titanium", "pro"],
  },
  {
    title: "Masuri Legacy Helmet",
    price: 4500,
    originalPrice: 5500,
    category: "helmets",
    brand: "masuri",
    image: "images/mhelmets.png",
    images: ["images/mhelmets.png"],
    rating: 4.8,
    reviews: 30,
    description: "Traditional cloth covered helmet with steel grille.",
    stock: 8,
    sizes: ["M", "L"],
    colors: ["Navy"],
    tags: ["safety", "traditional", "steel"],
  },

  // --- SHOES ---
  {
    title: "Kookaburra KC 2.0 Spikes",
    price: 4999,
    originalPrice: 6999,
    category: "shoes",
    brand: "kookaburra",
    image: "images/shoes.png",
    images: ["images/shoes.png"],
    rating: 4,
    reviews: 98,
    description:
      "Durable spikes for turf wickets with excellent ankle support.",
    stock: 15,
    sizes: ["UK 7", "UK 8", "UK 9", "UK 10"],
    colors: ["White/Green"],
    tags: ["spikes", "footwear", "turf"],
  },
  {
    title: "Adidas Vector Mid",
    price: 8999,
    originalPrice: 12999,
    category: "shoes",
    brand: "adidas",
    image: "images/ashoes.png",
    images: ["images/ashoes.png"],
    rating: 5,
    reviews: 120,
    description: "Premium bowling spikes used by fast bowlers worldwide.",
    stock: 4,
    sizes: ["UK 8", "UK 9", "UK 10", "UK 11"],
    colors: ["White/Blue"],
    tags: ["spikes", "bowling", "fast-bowler"],
  },
  {
    title: "Asics Gel Peake Rubber",
    price: 5500,
    originalPrice: 6500,
    category: "shoes",
    brand: "asics",
    image: "images/asicshoes.png",
    images: ["images/asicshoes.png"],
    rating: 4.8,
    reviews: 65,
    description: "Rubber studs perfect for hard wickets and artificial turf.",
    stock: 10,
    sizes: ["UK 7", "UK 8", "UK 9", "UK 10"],
    colors: ["White/Black"],
    tags: ["rubber-sole", "all-rounder", "footwear"],
  },

  // --- BAGS & KITS ---
  {
    title: "SG Teampak Wheelie Bag",
    price: 3999,
    originalPrice: 5499,
    category: "bags",
    brand: "sg",
    image: "images/bags.png",
    images: ["images/bags.png"],
    rating: 5,
    reviews: 112,
    description: "Large capacity wheelie bag. Fits pads, bats, and helmet.",
    stock: 20,
    sizes: ["Standard"],
    colors: ["Blue/Black"],
    tags: ["kitbag", "storage", "wheelie"],
  },
  {
    title: "BAS Players Complete Kit",
    price: 12999,
    originalPrice: 18999,
    category: "kits",
    brand: "bas",
    image: "images/baskit.png",
    images: ["images/baskit.png", "images/kbags.png"],
    rating: 4.5,
    reviews: 89,
    isNewArrival: true,
    description: "Full kit including Bat, Pads, Gloves, Helmet, and Bag.",
    stock: 2,
    sizes: ["Adult", "Youth"],
    colors: ["Multicolor"],
    tags: ["full-kit", "bundle", "value"],
  },
  {
    title: "SG Junior Cricket Kit",
    price: 6999,
    originalPrice: 8999,
    category: "kits",
    brand: "sg",
    image: "images/junior.png",
    images: ["images/junior.png"],
    rating: 4.8,
    reviews: 210,
    description:
      "Perfect starter kit for ages 10-14. Includes Kashmir willow bat.",
    stock: 5,
    sizes: ["Size 4", "Size 5", "Size 6"],
    colors: ["Blue/Orange"],
    tags: ["junior", "starter", "kit"],
  },
];

module.exports = async (req, res) => {
  try {
    if (!process.env.MONGO_URI) throw new Error("MONGO_URI missing");
    await mongoose.connect(process.env.MONGO_URI);

    // 1. DELETE OLD DATA
    await Product.deleteMany({});

    // 2. INSERT NEW DATA
    const insertedProducts = await Product.insertMany(seedProducts);

    // 3. AUTO-LINK "FREQUENTLY BOUGHT TOGETHER" (The Logic)
    // We filter the inserted products to find categories
    const bats = insertedProducts.filter((p) => p.category === "bats");
    const balls = insertedProducts.filter((p) => p.category === "balls");
    const gloves = insertedProducts.filter((p) => p.category === "gloves");
    const pads = insertedProducts.filter((p) => p.category === "pads");
    const helmets = insertedProducts.filter((p) => p.category === "helmets");

    // Loop through bats and link them to a Ball and a Glove
    for (let bat of bats) {
      // Add random ball ID if available
      if (balls.length > 0) {
        bat.frequentlyBoughtTogether.push(balls[0]._id);
      }
      // Add random glove ID if available
      if (gloves.length > 0) {
        bat.frequentlyBoughtTogether.push(gloves[0]._id);
      }
      await bat.save(); // Update the bat in DB
    }

    // Link Kits to Balls
    const kits = insertedProducts.filter((p) => p.category === "kits");
    for (let kit of kits) {
      if (balls.length > 0) {
        kit.frequentlyBoughtTogether.push(balls[0]._id);
        await kit.save();
      }
    }

    res.status(200).json({
      message: "✅ Database seeded successfully with Tags and FBT links!",
      count: insertedProducts.length,
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: error.message });
  }
};
